CREATE DATABASE IF NOT EXISTS harmonica_tabs; 

USE harmonica_tabs;

CREATE TABLE IF NOT EXISTS logins (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`uuid` VARCHAR(16) NOT NULL,
	`email` VARCHAR(32) NOT NULL,
	`username` VARCHAR(32) NOT NULL,
	`password` VARCHAR(64) NOT NULL,
	`created_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
	PRIMARY KEY (id), 
	UNIQUE (UUID), 
	UNIQUE (email) 
);